### ISSUE TITLE
System.NullReferenceException ... why?

### ISSUE THREAD

**Issue by HazelnutBread** [Kagamia/WzComparerR2#119]
![5](https://user-images.githubusercontent.com/58882766/70849703-1f3d8880-1ebd-11ea-85ea-31f9f8c26d12.jpg)

**Comment by Kagamia** [comment]
可以给出具体的复现步骤嘛？（如wc版本，客户端版本，打开的wz节点等详细过程）

**Comment by HazelnutBread** [comment]
Thank you! solved!

**Comment by DZGUAN** [comment]
我也是这个问题,是不是要安装什么插件?

**Comment by Kagamia** [comment]
@DZGUAN maprender依赖d3d11, d2d, dwrite等组件，请检查操作系统内是否安装了dinput1_3.dll

对于32位系统，检查 %systemroot%\system32\dinput1_3.dll
对于64位系统，32位程序(wcr2.exe)，检查%systemroot%\syswow64\dinput1_3.dll
对于64位系统，64位程序(wcr2.anycpu.exe)，检查%systemroot%\system32\dinput1_3.dll

如果没有，解决方法如下(任选其一)：
1> 如果对windows操作系统不是很了解，请直接安装完整directx runtime。因为最新的windows发布版(win10)中不包含dx9或更老旧的运行库
2> 可以在第三方网站中独立下载上面缺失的dll，并且放置在对应的文件夹里，重启wcR2重新尝试。

**Comment by Kagamia** [comment]
After a series of update, the typical exception stacktrace comes out:

![image](https://user-images.githubusercontent.com/10445904/76700098-d4ffb980-66ee-11ea-9beb-477f1c30eb8e.png)

**Comment by charlescao460** [comment]
Same error when running MapRendererV2 under Release builds. Debug configuration works fine. 

![image](https://user-images.githubusercontent.com/33741854/84371429-a38c7200-aba7-11ea-937b-da76d407169a.png)

The Exception was actually thrown from [WzComparerR2.Config::GetSectionName(Type type)](https://github.com/Kagamia/WzComparerR2/blob/f6ecfb18cae661f125a189e527feea1964f5bda8/WzComparerR2.Common/Config/ConfigManager.cs#L98), which is hard to debug because there is very few debug information about type for Release build.

**Comment by KENNYSOFT** [comment]
Still occurs in WzComparerR2.anycpu.exe, I'll make a PR for fix that.
