### ISSUE TITLE
关于冷却时间表述的一点建议

### ISSUE THREAD

**Issue by Fyllan** [Kagamia/WzComparerR2#136]
现在WZ节点里面的冷却时间有两种，一种#cooltime，应该是秒之类的，还有一种是#cooltimeMS，是毫秒，但是显示出来会让人感觉是秒，如果修正不麻烦的话，建议在渲染的时候转换成秒。

**Comment by Kagamia** [comment]
可以提供具体出现问题的技能截图或id嘛？

这个问题需要商榷，因为有些渲染是由string.wz自身提供的，wcR2没有能力去篡改它的表述。

**Comment by Fyllan** [comment]
韩测最新版本，技能节点40001，技能ID 400011131

![skill_400011131](https://user-images.githubusercontent.com/42598456/85122217-29bc4e80-b261-11ea-87ea-634e56244a07.png)

**Comment by Kagamia** [comment]
这显然就是我描述的“wz本来如此”，wc没有什么可做的。

**Comment by Fyllan** [comment]
了解，那就这样吧。

**Comment by Sunaries** [comment]
For that particular skill the `cooltimeMS` is set to 2500. Currently, WzComparerR2 cannot convert milliseconds to seconds, so that's why you read it as '2500 seconds', but it should be '2.5 seconds'.

Someone else fixed this: 
![](https://cdn.discordapp.com/attachments/345081079578755086/723606353289019442/image0.png)
