### ISSUE TITLE
Idea/Suggestion for Chara Sim: Visual window to view equipment etc.

### ISSUE THREAD

**Issue by Dban1** [Kagamia/WzComparerR2#140]
Hi, one of the main gripes I have when making avatars is that browsing the equipment node by node is hard to see the full collection of equipment that we can equip on our characters. I'm wondering if there are/were any plans to make a visual window that lists all the icons of the equipment so we can browse more easily? I'm not too familiar with the source code, but how hard would it be to make a window that displays these icons and allow us to select them? (Similar to Bannedstory/maplestory.design)

One idea to simplify it would be that it would be sufficient to just show the icons of the selected node. For example, I don't need a full interface that can choose to select Hair/Face/Longcoat/etc. Maybe just list the sub-members of the selected parent node. So like I select Hair, then the window pops up that display all the hair.

As there are no quality character designers left online because of takedowns by Nexon, it would be great if we could add more features to WzComparerR2 to have our own local simulator with more quality of life features like this

**Comment by Kagamia** [comment]
An good alternative is to use [momiji](https://github.com/chengse66/momiji) (note that the link is a fork version) but I'm not sure if it is compatible with the latest wz files.

I'm very sorry to say that wcR2 have no further development plan about it, because I have to work for food and I can share only little time on bug fixing.😢

**Comment by Dban1** [comment]
I see, sad to hear about the development plans, but all the best in your work! I don't mind trying to help make PRs to include more features to the program I love but I'm quite lost as to how to make a Windows Form link to the node to retrieve the info.

I tried Momiji before but it keeps crashing now :(

**Comment by Kagamia** [comment]
wcR2 UI is built with [DotNetBar](http://www.devcomponents.com/dotnetbar/download.aspx).
You'd better to download full SDK installer to perform drag-drop experience on VisualStudio.

It will be a hard work because the UI designer seems not to be stable enough, I ever want to refactor all UI to WPF (also for git friendly and multi-language support) but I'm not familiar with xaml.

**Comment by Elem8100** [comment]
https://github.com/Elem8100/WzComparerR2-Plus
