### ISSUE TITLE
Questions about CharaSim

### ISSUE THREAD

**Issue by OniOniOn-** [Kagamia/WzComparerR2#153]
1. What does `CharaProp.Smart` mean?
2. What's difference between `buffAdd` and `eBuffAdd`? Example is appreciated.
3. `ignoreMobDefR` and `finalDamR` has fractional values in game (85.7%), but is represented as int. Does wcr code need changes to simulate modern in-game values properly?

**Comment by Kagamia** [comment]
The character stat simulator module was not completely ported from WzComparerV1, and has not updated since BigBang.

`CharaProp.Smart`, I totally forgot how it is used :( maybe some skill or item buffs contains the smart flag.
`eBuffAdd` is not acceptable to the stat % from potentials. (maple heros?)
for pre-bb version `ignoreMobDefR` and `finalDamR` are only from potentials and some skills, and only have integer values.

wcr2 has no plan to maintain it, because it is too complex to simulate perfectly, and it is useless for a 17-years-old game.
