### ISSUE TITLE
Medal style bug

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#18]
I'll just post issues in separate posts as this is better to navigate.

For my GMS version, I have a **Stable** and **Unstable** version. The difference is that with Unstable version I can experiment with the code that you and KENNYSOFT provide. My GMS version is based of KENNYSOFT's Korean build.

So far in my Stable version (without the codes of https://github.com/Kagamia/WzComparerR2/commit/f0845fc517392c0040ae653d466cdd96d7ad8749, https://github.com/Kagamia/WzComparerR2/commit/459b75e005e5c71bf457a4d33f3bf70b24a8c5d0 and https://github.com/Kagamia/WzComparerR2/commit/2e3af7057d4b784a10bf000ba536eb9255d2ffc6) I simulate the following results:

![pinkbean](https://cdn.discordapp.com/attachments/236180502200057856/266261382704529408/1142840_stable.png)![queen](https://cdn.discordapp.com/attachments/236180502200057856/266261384302559232/1142866_stable.png)

However, when I add your new code to my Unstable version I will get the following results:
![pinkbean](https://cdn.discordapp.com/attachments/236180502200057856/266261383224492033/1142840_unstable.png)![queen](https://cdn.discordapp.com/attachments/236180502200057856/266261388933070848/1142866_unstable.png)

How can it be fixed to my Stable version without adding all the other code from your recent commits? Since I am not so sure if your code and that of KENNYSOFT will conflict.

**Comment by Kagamia** [comment]
There' re two difference between these version:
1> low-level text renderer engine, GDI or GDI+
2> Graphics.TextRenderingHint, ClearType or AntiAlias

I've wrote a standalone program to compare them, here is it:
````C#
	var bmp = new Bitmap(500,300);
	var g = Graphics.FromImage(bmp);
	g.Clear(Color.DarkSlateGray);
	int y = 20;
	var font = new Font("Arial", 11f, FontStyle.Regular, GraphicsUnit.Pixel);
	var fmt = StringFormat.GenericTypographic.Clone() as StringFormat;
	
	string text = "Ambition 90, Willpower 90, Charm 90 EXP can be obtained once when equipped.";
	
	foreach(System.Drawing.Text.TextRenderingHint trh in Enum.GetValues(typeof(System.Drawing.Text.TextRenderingHint))) {
		g.TextRenderingHint = trh;
		g.DrawString(trh.ToString(), font, Brushes.White, 0, y);
		g.DrawString(text, font, Brushes.Orange, 20, y+12);
		TextRenderer.DrawText(g, text, font, new Point(20, y+24), Color.Orange);
		y+=36;
	}
````
![8afd8a2d0708283810a1a381b899a9014d08f17f](https://cloud.githubusercontent.com/assets/10445904/21653460/338353e4-d2ec-11e6-80ed-9b8e95c2cec8.png)

In short words, 
````C#
g.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAliasGridFit; 
````
makes texts more clear.
The advance of space character in GDI is a bit shorter than those in GDI+.

Font fallback in GDI+ looks better than GDI, that's why I use GDI+ mainly in CMS version.

`GearGraphics.DrawString` could be replaced with new version if there's no serious bugs. It support both GDI and GDI+ text rendering engine, but it measures with GDI+ and fixed-pitch fallback function.

So, how you merge these code is depend on what you like. :)

**Comment by Sunaries** [comment]
@Kagamia Using `AntiAliasGridFit` makes the font not similar to official GMS version. You can definitely see the font has changed even though it is Arial.

**Comment by Kagamia** [comment]
Yes you get the right way. 👍 

Usually, alter and recovery statement is written like this:
````C#
var oldVal = g.TextRenderingHint;
g.TextRenderingHint = blablabla
// draw...
g.TextRenderingHint = oldVal;
````

**Comment by Sunaries** [comment]
@Kagamia I see the same happening to titles

![title](https://cdn.discordapp.com/attachments/244458112864485378/266646605829111811/3700404.png)

Where can I find the code for title so I can add the same method to fix this issue?
