### ISSUE TITLE
Etc.wz in GMS client file is not decoded correctly

### ISSUE THREAD

**Issue by wwj010** [Kagamia/WzComparerR2#215]
![image](https://user-images.githubusercontent.com/13106792/194219549-450f37d2-26bb-439d-b7d8-b3d44d068ebf.png)
This shows up in GMS v236

**Comment by Kagamia** [comment]
I don't have a GMS client, hope someone could provide a sample file to me :>

**Comment by Kagamia** [comment]
Only occurs when `WzVersionDetection` is set to `default`.
![image](https://user-images.githubusercontent.com/10445904/194593978-66f9a57c-c398-4d80-8228-d17fc6bbb15f.png)
As a workaround you can set it to `fast`.

The root cause is a little complicated, [Wz_Image.TryDetectLuaEnc()](https://github.com/Kagamia/WzComparerR2/blob/a6e7a05fe32192f8f2867720f642875207bd6e54/WzComparerR2.WzLib/Wz_Image.cs#L360) method has some side effect, it will overwrite the crypto keys in Wz_Structure level, and finally cause the next Wz loading with a wrong crypto key.

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/194686535-f3da7137-e79c-4eb3-aaef-cd356d57af2e.png)

KMS version is not affected. (I've loaded with WzVersionDetection = default)

You can refer:

* KENNYSOFT@e21868553f9b6f50044def6a78b7b682f89e2045 for KENNYSOFT#73
* KENNYSOFT@74cdfadd1b3b6b90c2d8a723ba3278827e02181a for KENNYSOFT#74

**Comment by Kagamia** [comment]
@KENNYSOFT  cool! really helps.
